binary=containers

all:
	g++ -std=c++11 containers.cpp -o $(binary)

fixa:
	g++ -std=c++11 -DFIX_A containers.cpp -o $(binary)

fixb:
	g++ -std=c++11 -DFIX_B containers.cpp -o $(binary)

clean:
	rm *.o $(binary)
